const { test, expect } = require('@playwright/test');

const near=(a,b,eps=.8)=>expect(Math.abs(a-b)).toBeLessThan(eps);
async function fresh(page){await page.addInitScript(()=>localStorage.clear());await page.goto('http://127.0.0.1:4173/v3-preview.html');await page.waitForFunction(()=>Boolean(window.__StickerV3Diagnostics?.features?.smartDimensions));await page.waitForTimeout(120);}
async function addVerticalGuide(page,ratio=.35){const paper=await page.locator('.paper').boundingBox(),ruler=await page.locator('#rulerVertical').boundingBox();await page.mouse.move(ruler.x+ruler.width/2,paper.y+paper.height/2);await page.mouse.down();await page.mouse.move(paper.x+paper.width*ratio,paper.y+paper.height/2,{steps:4});await page.mouse.up();await expect(page.locator('.user-guide-hit')).toHaveCount(1);}

test('red guide can be selected, deleted with Delete, and restored with Undo',async({page})=>{await fresh(page);await addVerticalGuide(page);const hit=page.locator('.user-guide-hit');await hit.click({force:true,position:{x:10,y:100}});await expect(page.locator('.user-guide.selected-guide')).toHaveCount(1);await page.keyboard.press('Delete');await expect(page.locator('.user-guide-hit')).toHaveCount(0);await page.keyboard.press('Control+z');await expect(page.locator('.user-guide-hit')).toHaveCount(1);});

test('guide right click opens explicit menu instead of silently deleting',async({page})=>{await fresh(page);await addVerticalGuide(page);await page.locator('.user-guide-hit').click({button:'right',force:true,position:{x:10,y:100}});await expect(page.locator('#guideContextMenu')).toBeVisible();await expect(page.locator('[data-guide-action="delete"]')).toContainText('ลบเส้นไกด์');await page.locator('[data-guide-action="delete"]').click();await expect(page.locator('.user-guide-hit')).toHaveCount(0);});

test('Smart Dimension on a guide is persistent and follows paper size from the chosen edge',async({page})=>{await fresh(page);await addVerticalGuide(page,.45);await page.click('#guideMeasureBtn');await page.locator('.user-guide-hit').click({force:true,position:{x:10,y:120}});const paper=await page.locator('.paper').boundingBox();await page.mouse.click(paper.x+paper.width-5,paper.y+paper.height/2);await page.fill('#guideDistanceInput','50');await page.click('#guideMeasureApplyBtn');let dims=await page.evaluate(()=>window.__StickerV3Diagnostics.getDimensions());expect(dims).toHaveLength(1);expect(dims[0].referenceEdge).toBe('right');let guides=await page.evaluate(()=>window.__StickerV3Diagnostics.getGuides());near(guides.x[0],630);await page.fill('#paperWidth','800');await page.dispatchEvent('#paperWidth','input');await page.waitForTimeout(160);guides=await page.evaluate(()=>window.__StickerV3Diagnostics.getGuides());near(guides.x[0],750);await expect(page.locator('[data-driving-dimension]')).toHaveCount(1);});

test('Smart Dimension moves an object edge and keeps it constrained after paper resize',async({page})=>{await fresh(page);await page.click('#addFrameBtn');const frame=page.locator('.frame-shape').last();const fb=await frame.boundingBox();await page.click('#guideMeasureBtn');await frame.click({force:true,position:{x:Math.max(2,fb.width-2),y:fb.height/2}});const paper=await page.locator('.paper').boundingBox();await page.mouse.click(paper.x+paper.width-4,paper.y+paper.height/2);await page.fill('#guideDistanceInput','40');await page.click('#guideMeasureApplyBtn');let p=await page.evaluate(()=>window.__StickerV3Diagnostics.getProject()),d=p.designs.at(-1),o=p.objects.find(x=>d.objectIds.includes(x.id)&&x.type==='frame'),pl=p.placements.find(x=>x.designId===d.id),tr=pl.transforms[o.id];near(tr.x+o.size.w,p.paper.w-40);await page.fill('#paperWidth','760');await page.dispatchEvent('#paperWidth','input');await page.waitForTimeout(160);p=await page.evaluate(()=>window.__StickerV3Diagnostics.getProject());d=p.designs.at(-1);o=p.objects.find(x=>d.objectIds.includes(x.id)&&x.type==='frame');pl=p.placements.find(x=>x.designId===d.id);tr=pl.transforms[o.id];near(tr.x+o.size.w,720);});

test('double clicking a driving dimension edits its value and Delete removes only the constraint',async({page})=>{await fresh(page);await addVerticalGuide(page,.25);await page.click('#guideMeasureBtn');await page.locator('.user-guide-hit').click({force:true,position:{x:10,y:120}});const paper=await page.locator('.paper').boundingBox();await page.mouse.click(paper.x+5,paper.y+paper.height/2);await page.fill('#guideDistanceInput','50');await page.click('#guideMeasureApplyBtn');const label=page.locator('.driving-dim-label-bg');await label.dblclick({force:true});await expect(page.locator('#guideMeasurePanel')).toBeVisible();await page.fill('#guideDistanceInput','80');await page.click('#guideMeasureApplyBtn');let guides=await page.evaluate(()=>window.__StickerV3Diagnostics.getGuides());near(guides.x[0],80);await label.click({force:true});await page.keyboard.press('Delete');expect(await page.evaluate(()=>window.__StickerV3Diagnostics.getDimensions())).toHaveLength(0);guides=await page.evaluate(()=>window.__StickerV3Diagnostics.getGuides());near(guides.x[0],80);});

test('center relation keeps text centered when frame size changes',async({page})=>{await fresh(page);await page.click('#addItemBtn');await page.locator('#frameEnabled').evaluate(el=>{el.checked=true;el.dispatchEvent(new Event('change',{bubbles:true}));});await expect(page.locator('#centerRelationBtn')).toBeVisible();await page.click('#centerRelationBtn');expect(await page.evaluate(()=>window.__StickerV3Diagnostics.getRelations())).toHaveLength(1);await page.fill('#frameWidth','300');await page.dispatchEvent('#frameWidth','input');await page.waitForTimeout(80);const info=await page.evaluate(()=>{const p=window.__StickerV3Diagnostics.getProject(),d=p.designs[0],t=p.objects.find(o=>d.objectIds.includes(o.id)&&o.type==='text'),f=p.objects.find(o=>d.objectIds.includes(o.id)&&o.type==='frame'),pl=p.placements.find(x=>x.designId===d.id),tt=pl.transforms[t.id],ft=pl.transforms[f.id];return{tcx:tt.x+t.size.w/2,tcy:tt.y+t.size.h/2,fcx:ft.x+f.size.w/2,fcy:ft.y+f.size.h/2};});near(info.tcx,info.fcx);near(info.tcy,info.fcy);await expect(page.locator('#centerRelationBtn')).toHaveClass(/active/);});
